### PR TITLE
Fix OpenBench support 

### PR DESCRIPTION
**Pull request by eduherminio**
Allow renaming executable using `ExecutableName` without an .exe suffix, leaving the moving part to OB
This mimics Lynx `Makefile` behavior

### CODE REVIEW

**Comment by eduherminio** [comment]
Not needed any more I guess

**Comment by Timmoth** [comment]
Thanks for making the PR @eduherminio - could you re-open please? I got a bit side tracked with another issue last night, but I still intend to review and merge today, it certainly looks alot cleaner then my current solution - and If i can offload the make logic into the CSPROJ i'll be happy

**Comment by eduherminio** [comment]
Oh, sure thing @Timmoth.
Just be aware that this solution is far from perfect: it doesn't support actual dirs for the `EXE` as you were trying to do (as you noticed it's directly used as `ExecutableName`) and it expects the executable name without the extension (or you may end up with `soopling.exe.exe`).
It does the job though.

Feel free to contribute back if you improve it further 😄

**Comment by Timmoth** [comment]
Thank you for this @eduherminio

I finally got around to setting up OpenBench properly on a VPS and your solution worked a charm.

Now I just have to make sure it all works fine on Linux

**Pull request merged**
